
INSERT INTO hibernate_search.product (id,create_date,last_modified_date,description,name) VALUES
                                                                                                                           ('036814a2-1349-4c4a-b398-4e2387eea5b1','2022-07-05','2022-08-02','Áo Hoodie Unisex College Hoodie với Chất liệu Nỉ Ngoại tốt; mang phong cách thời trang thời thượng các bạn trẻ; đặc biệt không những giúp bạn giữ ấm trong mùa lạnh mà còn có thể chống nắng, chống gió, chống bụi, chống rét, chống tia UV cực tốt.','Unisex College Hoodie'),
                                                                                                                           ('036814a2-1349-4c4a-b398-4e2387eea5b2','2022-07-05','2022-08-02','ao ao ao yeu','Unisex College Hoodie'),
                                                                                                                           ('036814a2-1349-4c4a-b398-4e2387eea5b3','2022-07-05','2022-08-02','ao yeu','Unisex College Hoodie'),
                                                                                                                           ('036814a2-1349-4c4a-b398-4e2387eea5b4','2022-07-05','2022-08-02','yeu','Unisex College Hoodie'),
                                                                                                                           ('036814a2-1349-4c4a-b398-4e2387eea5b5','2022-07-05','2022-08-02','ao','Unisex College Hoodie'),
                                                                                                                           ('036814a2-1349-4c4a-b398-4e2387eea5bư','2022-07-05','2022-08-02','yeu yeu ao ','Unisex College Hoodie'),
                                                                                                                           ('0eb0964d-bb4e-484a-af4b-8b6e1e4f67a1','2022-07-05','2022-08-02','Áo hoodie được làm từ chất liệu nỉ ngoại mềm mịn dày dặn, co giãn, thông thoáng, đảm bảo cảm giác thoải mái, dễ chịu khi mặc. Đường may tinh tế, tỉ mỉ trong từng chi tiết. Thiết kế đơn giản, dễ mặc, dễ phối đồ.  Chất lượng sản phẩm tốt, giá cả hợp lý. ','Unisex Supply Hoodie'),
                                                                                                                           ('343fefbb-7a7d-4d2a-9e8e-a3614780f57d','2022-07-05','2022-08-02','Với đặc điểm dễ mặc dễ mix đồ, mặc cực thoải mái thoáng mát, lại mang đến vẻ quyến rũ không gì cưỡng nỗi. Cực xinh khi kết hợp với chân váy và áo khoác mỏng hoặc mặc kèm quần cạp cao. Khách hàng đều hài lòng 100% ngay khi nhận được hàng.','Áo croptop LA'),
                                                                                                                           ('3974f4e3-7a01-472f-9e93-256b54168f8f','2022-07-05','2022-08-08','Unisex Cruiser Hoodie là sản phẩm mới nhất, chất liệu may tốt, được gia công trực tiếp tại Việt Nam. Form Basic cực kỳ dễ mặc, dễ phối đồ. Có thể mặc nhà hoặc đi chơi đều được.','Unisex Cruiser Hoodie'),
                                                                                                                           ('481639ec-c394-479b-93ca-4bfe0f67b837','2022-07-05','2022-08-08','Sản phẩm này được làm từ sợi bông hữu cơ. Việc sản xuất loại sợi bông này giúp giảm thiểu tiêu thụ nước và hóa chất và giúp cho sản phẩm này thân thiện với môi trường và con người.','Áo thun form nhỏ'),
                                                                                                                           ('4de82684-c0fe-496f-946d-d642ec91bee1','2022-07-05','2022-07-24','Áo thun fuser, hút mồ hôi tốt, thoải mái cho người hay vận động, phải thường xuyên di chuyển trong môi trường nóng bức','Áo thun fuser'),
                                                                                                                           ('61b6c9a6-c12c-41bd-91ad-d799dd476abb','2022-07-05','2022-08-08',' Với chất liệu thun cực mát, thấm hút tốt, sản phẩm sẽ mang đến cho bạn cảm giác dễ chịu và thoải mái những lúc nghỉ ngơi, thư giãn tại nhà.và những lúc bạn đi chơi,đi dạo,đi shop.','Áo thun nữ'),
                                                                                                                           ('782b3189-bff2-4751-8e6f-0a7d5c824e61','2022-07-05','2022-08-08','Áo hoodies champion mới cho mùa thu đông  này. Với form rộng dáng thụng mặc cực thích, layer rách và chun cổ áo + tay áo tinh tế tạo điểm nhấn đặc biệt. Chất liệu nỉ bông  mịn mặc cực thích, ae diện đôi hoặc mặc nhóm cùng đi học, đi chơi hay đi du lịch','Áo hoodies champion'),
                                                                                                                           ('85d4c7a8-edd9-43db-9176-dc3ed7634665','2022-07-05','2022-08-08','Streeter Hoodie Dress, với đường may liền, mảnh dài qua hông, thể hiện phong cách casual nên rất thích hợp cho các hoạt động ngoại khóa ngoài trời, đi học, đi làm và đi chơi cùng gia đình hoặc bạn bè.','Streeter Hoodie Dress'),
                                                                                                                           ('87334855-3594-4a7f-89d7-b2eae7c6129e','2022-07-05','2022-08-02','Tuy là sản phẩm tự gia công, số lượng thường sẽ không nhiều, nhưng áo thun PODOC luông đảm bảo về chất lương cho người dùng. Với chất liệu cotton, thoáng khí, hút mồ hôi và đặc biệt không bị phai màu.','Áo thun PODOC'),
                                                                                                                           ('8a3e8974-2df8-4edd-ac2d-aef26ce79bc9','2022-07-11','2022-08-02','Chất liệu dày dặn, mềm mịn, thích hợp mặc mùa thu đông, tiết trời se se lạnh Kiểu dáng hoodie chui đầu có mũ trùm cá tính. Họa tiết in hoa cúc mặt lưng sắc nét, không phai màu.','Unisex Heavy Blend Hooded'),
                                                                                                                           ('8b0cc28c-dd22-4f04-8a4d-948079ba9768','2022-07-05','2022-08-02','
Men''s Organic Sparker thiết kế ôm body, phù hợp với người có body cân đối hoặc hơi gầy. Sản phẩm được chuộng nên đảm bảo sẽ luôn có sẵn ngay khi đặt đơn.','Men''s Organic Sparker'),
                                                                                                                           ('a549eaa8-cd41-437f-a38d-dca6ad1a1a68','2022-07-05','2022-08-08','Áo sweater mỏng, phù hợp cho những người có dáng nhỏ, cao, thiết kế ôm body đặc biệt cho nam giới. Phù hợp khi ra đường, đi tập gym và có thể phối với hầu hết các loại đồ','Men’s Base Longsleeve Tee'),
                                                                                                                           ('a97f0f33-3934-45ae-bd71-76e270919b42','2022-07-05','2022-08-08','Áo form cao, dành cho những bạn nam có phong cách ăn mặc trẻ trung, năng động. Đồng thời thiết kế rộng lưng giúp che đi khuyết điểm dài lưng, phù hợp cho các bạn nữ.','Áo form cao'),
                                                                                                                           ('a9aeb9d8-fba9-4fdb-8823-06af4e2c3be0','2022-07-03','2022-08-02','Chất liệu thun cotton thoáng mát mặc thoải mái không bị nóng, không xù lông khi sử dụng lâu.
Thiết kế thời trang, trẻ trung năng động phù hợp xu hướng hiện nay
Đường may tinh tế sắc sảo ','Unisex Garment-Dyed'),
                                                                                                                           ('b46b1c8a-250c-4f22-930d-65783a1870c2','2022-07-05','2022-08-02','Long Sleeve Crewneck Tee là áo sweater được thiết kế theo phong cách unisex, dựa trên dáng của những bạn nam cao, vai rộng, với nữ giới thì phù hợp với mọi dáng người.','Long Sleeve Crewneck Tee'),
                                                                                                                           ('b8e4aba8-7e1b-495e-b749-5aa9be27bed1','2022-07-05','2022-08-08','Women''s Crop Tee được thiết kế có độ dài ngắn đến ngang eo, để lộ phần eo, có thể dài hay ngắn hơn một chút tùy từng mẫu áo. Chính vì kiểu thiết kế khá đặc trưng này nên áo croptop chỉ phổ biến với nữ giới. ','Women''s Crop Tee '),
                                                                                                                           ('c2637594-4f19-4117-beb2-f4d60322a85c','2022-07-05','2022-08-08','Áo thun nữ, form vuông, trẻ trung năng động, dễ dàng phối với nhiều phong cách ăn mặc khác nhau','Women''s Favorite Tee'),
                                                                                                                           ('c287dc96-6b90-4a88-8306-b6c7f0a29323','2022-07-05','2022-08-08','Men''s Long Sleeve Crew Tee là một item không thể thiếu trong mua thu đông, vừa thời trang vừa ấm áp. Với thiết kế dáng ôm, tay và gấu bo gọn gàng. Đây chính là sự lựa chọn hoàn hảo để kết hợp với tất cả các outfit của bạn.','Men''s Long Sleeve Crew Tee'),
                                                                                                                           ('c654a5fc-4f8b-4ce7-8781-99d1834bee57','2022-07-05','2022-08-08','Áo crop top trẻ trung năng động, được thiết kế chuyên dụng cho những bạn thường xuyên vận động. Đường may tinh xảo, thiết kế ôm nhưng không quá chật.','Women''s Dancer Cropped'),
                                                                                                                           ('cf315b21-9538-4978-a4ab-3cfa3b368074','2022-07-05','2022-08-02','Áo thể thao nam được thiết kế theo đúng form chuẩn của nam giới Việt Nam.
Sản phẩm chính là mẫu thiết kế mới nhất cho xu hướng mùa hè này.
Thiết kế đơn giản, dễ dàng phối trang phục đi tập Gym, thể thao, đi chơi, đi dạo phố.','Unisex Barnard Tank'),
                                                                                                                           ('dee733ce-a629-4273-b044-52fbaeae791f','2022-07-05','2022-08-08','Unisex Heavy Blend thiết kế theo kiểu áo dài tay form rộng, được sản xuất bằng các chất liệu dày dặn như vải nỉ. Áo khoác nỉ được đánh giá là một trong những trang phục linh hoạt và thoải mái, thời thượng và trẻ trung nhất.','Unisex Heavy Blend'),
                                                                                                                           ('ecf174fc-8a16-4ce9-874e-f65d5d51a695','2022-07-05','2022-08-02','Unisex Hooded Zip  được làm từ chất liệu vải bông, không quá bí, phù hợp mặc trong phòng lạnh hoặc khí trời mùa đông. Thiết kế trẻ trung, năng động, phù hợp khi đi làm ở công sở, hoặc đi dạo phố.','Unisex Hooded Zip'),
                                                                                                                           ('f9a29793-86dd-4d60-b3ca-08a8efb6eb4f','2022-07-05','2022-08-02','Thiết kế theo phong cách unisex, ôm sát body, yêu cầu loại vải dày, nên áo thường được mặc vào những dịp trời se lạnh hoặc mội trường phải ngồi nhiều máy lạnh.','Crewneck Sweatshirt');

